# TODO: Add Comments and IDs

name: "Check for Typos in Files"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4

      - name: Check Spelling of All Files
        uses: crate-ci/typos@master
        continue-on-error: true
        with:
          files: ./
